version: '3'

services:
  sleek-airflow:
    image: airflowtooltorial:latest

    volumes:
      - ./airflow:/opt/airflow
      - ./data:/opt/data

    ports:
      - "8080:8080"

    command: airflow standalone